# Site settings
title: kpwiki
url: "https://kpwiki.github.io"
baseurl: ""
description: >
    대한민국 약전 검색 + 국외약전 수재 여부 확인

# My information
email: kpwiki12@gmail.com
author: kpwiki
profile: 대한약전
twitter_username: kpwiki
github_username: kpwiki
disqus_shortname: kpwiki

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: kpwiki
  shortname: kpwiki

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/kpwiki/kpwiki.github.io/blame/master/_wiki"
edit: "https://github.com/kpwiki/kpwiki.github.io/edit/master/_wiki"
issue: "https://github.com/kpwiki/kpwiki.github.io/issues/new"

timezone: "Asia/Seoul"
